miIlicon/WithFestival-BackEnd

src/main/java/com/festival/controller/WithFestivalController.java, src/main/java/com/festival/data/dto/request/FoodTruckRequest.java, src/main/java/com/festival/data/entity/FoodTruck.java, src/main/java/com/festival/data/repository/FoodTruckRepository.java, src/main/java/com/festival/service/WithFestivalService.java, src/main/java/com/festival/service/impl/WithFestivalServiceImpl.java
(빨간줄은 캡처도구에서 잘못만졌슴다 ㅈㅅ ㅎ.ㅎ)
디렉터리 초기 설정을 위해 각 디렉토리별로 파일을 하나씩 생성하였습니다. 수정이 필요해보이는 부분은 리뷰 부탁드립니다.
common : 공통 컴포넌트 영역(Exception 관리, ErrorCode 관리... 등)
controller: 클라이언트 입출력 
data: DB에 접근가능하며 모든 레이어에 걸쳐 사용되는 데이터 
service: 비즈니스 로직 설계
=> 초기 디렉터리 설정을 위해 파일 셋팅

.github/CODEOWNERS
=> CodeOwner Auto Assign

src/main/java/com/festival/domain/info/festivalPub/controller/FestivalPubController.java, src/main/java/com/festival/domain/info/festivalPub/data/dto/FestivalPubReq.java, src/main/java/com/festival/domain/info/festivalPub/data/dto/reqest/PubRequest.java, src/main/java/com/festival/domain/info/festivalPub/data/dto/response/PubResponse.java, src/main/java/com/festival/domain/info/festivalPub/data/entity/FestivalPub.java, src/main/java/com/festival/domain/info/festivalPub/data/entity/file/PubImage.java, src/main/java/com/festival/domain/info/festivalPub/data/entity/pub/FestivalPub.java, src/main/java/com/festival/domain/info/festivalPub/data/entity/pub/PubState.java, src/main/java/com/festival/domain/info/festivalPub/repository/FestivalPubRepository.java, src/main/java/com/festival/domain/info/festivalPub/repository/PubImageRepository.java, src/main/java/com/festival/domain/info/festivalPub/service/FestivalPubService.java
=> feat: 주점 생성 로직 추가 (미완성) (#3)

src/main/java/com/festival/domain/foodTruck/controller/FoodTruckController.java, src/main/java/com/festival/domain/foodTruck/data/dto/request/FoodTruckRequest.java, src/main/java/com/festival/domain/foodTruck/data/dto/response/FoodTruckResponse.java, src/main/java/com/festival/domain/foodTruck/service/FoodTruckService.java, src/main/java/com/festival/domain/foodTruck/service/impl/FoodTruckServiceImpl.java
=> feat : foodTruck controller initialize (#16)

src/main/java/com/festival/domain/foodTruck/data/entity/FoodTruck.java, src/main/java/com/festival/domain/foodTruck/data/entity/FoodTruckImage.java, src/main/java/com/festival/domain/info/festivalPub/controller/PubController.java, src/main/java/com/festival/domain/info/festivalPub/data/entity/file/PubImage.java, src/main/java/com/festival/domain/info/festivalPub/repository/PubRepositoryCustom.java, src/main/java/com/festival/domain/info/festivalPub/repository/PubRepositoryImpl.java, src/main/java/com/festival/domain/info/festivalPub/service/PubService.java, src/main/java/com/festival/global/base/BaseTimeEntity.java, src/main/resources/application.yml
=> refactor: 주점 조회 로직 개선 (#23)

src/main/java/com/festival/common/vo/SearchCond.java, src/main/java/com/festival/domain/foodTruck/controller/FoodTruckController.java, src/main/java/com/festival/domain/foodTruck/data/dto/response/FoodTruckCreateResponse.java, src/main/java/com/festival/domain/foodTruck/data/dto/response/FoodTruckResponse.java, src/main/java/com/festival/domain/foodTruck/data/entity/FoodTruckImage.java, src/main/java/com/festival/domain/foodTruck/repository/FoodTruckCustomRepository.java, src/main/java/com/festival/domain/foodTruck/repository/FoodTruckRepository.java, src/main/java/com/festival/domain/foodTruck/repository/impl/FoodTruckRepositoryCustomImpl.java, src/main/java/com/festival/domain/foodTruck/service/FoodTruckService.java, src/main/java/com/festival/domain/foodTruck/service/impl/FoodTruckServiceImpl.java
FoodTruck 상세조회 및 목록조회 구현하였습니다. 목록조회 수호 잘먹었슴다 땡큐 베리 마취입니다. 👍
이슈 : #25
=> Feat : FoodTruck 상세조회, 목록 조회 구현 (#25)

src/main/java/com/festival/domain/film/controller/FilmController.java, src/main/java/com/festival/domain/film/repository/FilmRepository.java, src/main/java/com/festival/domain/film/service/FilmService.java
=> festivalFilm 단건, 전체 조회로직 구현

src/main/java/com/festival/domain/info/festivalPub/controller/PubController.java, src/main/java/com/festival/domain/info/festivalPub/data/dto/request/PubRequest.java, src/main/java/com/festival/domain/info/festivalPub/service/PubService.java
- 주점 입력 dto 에서 subFiles를 분리했습니다.
=> refactor: 주점 dto subFiles 분리 (#34)

src/main/java/com/festival/common/utils/ImageServiceUtils.java, src/main/java/com/festival/domain/foodTruck/controller/FoodTruckController.java, src/main/java/com/festival/domain/foodTruck/data/entity/FoodTruck.java, src/main/java/com/festival/domain/foodTruck/data/entity/FoodTruckImage.java, src/main/java/com/festival/domain/foodTruck/service/FoodTruckService.java, src/main/java/com/festival/domain/foodTruck/service/impl/FoodTruckServiceImpl.java, src/main/java/com/festival/domain/info/festivalPub/repository/PubRepositoryCustom.java, src/main/java/com/festival/domain/info/festivalPub/repository/PubRepositoryImpl.java, src/main/java/com/festival/domain/info/festivalPub/service/PubService.java
푸드트럭 Delete, Update 비즈니스 로직 구현하였습니다.
Pub관련 파일은 불필요 import 제거건으로 추가되었습니다.
=> Feat/40 푸드트럭 삭제 및 수정 구현

src/main/java/com/festival/domain/info/festivalPub/data/dto/response/PubResponse.java, src/main/java/com/festival/domain/info/festivalPub/data/entity/file/PubImage.java, src/main/java/com/festival/domain/info/festivalPub/service/PubService.java
- 주점 비즈니스로직의 수정, 삭제시에 파일 삭제가 되지않는 로직을 개선했습니다.
=> refactor: 주점 이미지 파일 수정,삭제 로직 개선 (#44)

src/main/java/com/festival/domain/fleaMarket/data/entity/FleaMarketImage.java, src/main/java/com/festival/domain/info/festivalPub/data/entity/file/PubImage.java
- 플리마켓의 연관관계를 맞춰줬습니다.
- 주점 수정로직을 기존 파일명으로 삭제하고 변경되도록 수정했습니다.
=> refactor: 주점의 메인파일 수정 로직 개선 (#50)

src/main/java/com/festival/domain/info/festivalEvent/controller/FestivalEventController.java, src/main/java/com/festival/domain/info/festivalEvent/data/entity/FestivalEvent.java, src/main/java/com/festival/domain/info/festivalEvent/data/entity/FestivalEventImage.java, src/main/java/com/festival/domain/info/festivalEvent/service/FestivalEventService.java
- 파일 수정 기능 구현
-> 원본 파일 삭제 후 데이터 수정하는 방식으로 구현
- 파일 삭제 기능 구현
=> Feature : FestivalEvent 파일 수정, 삭제 기능 구현

src/main/java/com/festival/domain/film/controller/FilmController.java, src/main/java/com/festival/domain/film/data/entity/Film.java, src/main/java/com/festival/domain/film/exception/FilmNotFoundException.java, src/main/java/com/festival/domain/film/service/FilmService.java, src/main/java/com/festival/global/exception/ErrorCode.java, src/main/java/com/festival/global/exception/GlobalExceptionAdvice.java
- 축제 영상 수정, 삭제 기능 구현
- 축제 영상 NotFound예외처리 추가
=> Feature : 축제 영상 수정, 삭제 기능 구현, NotFound예외처리 추가

build.gradle, src/main/java/com/festival/FestivalApplication.java, src/main/resources/application.yml
- Spring Security 의존성 추가
- 기능 제외(JWT기능 동작 확인 후에 켜겠습니다)
=> Config : Spring Security 의존성 추가, 기능 제외

src/main/java/com/festival/domain/fleaMarket/data/dto/request/FleaMarketRequest.java, src/main/java/com/festival/domain/fleaMarket/data/dto/response/FleaMarketListResponse.java, src/main/java/com/festival/domain/fleaMarket/data/dto/response/FleaMarketResponse.java, src/main/java/com/festival/domain/foodTruck/data/dto/request/FoodTruckRequest.java, src/main/java/com/festival/domain/foodTruck/data/dto/response/FoodTruckListResponse.java, src/main/java/com/festival/domain/foodTruck/data/dto/response/FoodTruckResponse.java, src/main/java/com/festival/domain/info/festivalEvent/data/dto/FestivalEventListRes.java, src/main/java/com/festival/domain/info/festivalEvent/data/dto/FestivalEventReq.java, src/main/java/com/festival/domain/info/festivalEvent/data/dto/FestivalEventRes.java, src/main/java/com/festival/domain/info/festivalPub/data/dto/request/PubRequest.java, src/main/java/com/festival/domain/info/festivalPub/data/dto/response/PubListResponse.java, src/main/java/com/festival/domain/info/festivalPub/data/dto/response/PubResponse.java
각 도메인별 foodTruckState, pubState와 같이 명시적으로 표기해주던 것을 모두 state로 통일합니다.
=> Refactor : DTO state수정

src/main/java/com/festival/domain/booth/controller/BoothController.java, src/main/java/com/festival/domain/booth/controller/dto/BoothListReq.java, src/main/java/com/festival/domain/booth/controller/dto/BoothReq.java, src/main/java/com/festival/domain/booth/controller/dto/BoothRes.java, src/main/java/com/festival/domain/booth/dto/BoothDto.java, src/main/java/com/festival/domain/booth/model/Booth.java, src/main/java/com/festival/domain/booth/model/BoothStatus.java, src/main/java/com/festival/domain/booth/model/BoothType.java, src/main/java/com/festival/domain/booth/repository/BoothCustomRepository.java, src/main/java/com/festival/domain/booth/repository/BoothRepository.java, src/main/java/com/festival/domain/booth/service/BoothService.java, src/main/java/com/festival/domain/booth/service/vo/BoothListSearchCond.java
- #100 
- 축제부스  도메인의 기본적인 CRUD 기능을 구현했습니다.
<hr>
<br>
=> [#100] 축제부스 CRUD설계

src/main/java/com/festival/domain/program/controller/ProgramController.java, src/main/java/com/festival/domain/program/dto/ProgramDto.java, src/main/java/com/festival/domain/program/dto/ProgramListReq.java, src/main/java/com/festival/domain/program/dto/ProgramListRes.java, src/main/java/com/festival/domain/program/dto/ProgramReq.java, src/main/java/com/festival/domain/program/dto/ProgramRes.java, src/main/java/com/festival/domain/program/model/Program.java, src/main/java/com/festival/domain/program/model/ProgramStatus.java, src/main/java/com/festival/domain/program/model/ProgramType.java, src/main/java/com/festival/domain/program/repository/ProgramCustomRepository.java, src/main/java/com/festival/domain/program/repository/ProgramCustomRepositoryImpl.java, src/main/java/com/festival/domain/program/repository/ProgramRepository.java, src/main/java/com/festival/domain/program/service/ProgramService.java, src/main/java/com/festival/domain/program/service/vo/ProgramSearchCond.java
- #96 
- 프로그램의 기본적인 CRUD 기능을 구현했습니다.
<hr>
<br>
=> [#96] PROGRAM(event/game) CRUD 설계 

src/main/java/com/festival/domain/bambooforest/controller/BambooForestController.java, src/main/java/com/festival/domain/bambooforest/service/BamBooForestService.java, src/main/java/com/festival/domain/booth/controller/BoothController.java, src/main/java/com/festival/domain/booth/controller/dto/BoothRes.java, src/main/java/com/festival/domain/booth/repository/BoothRepository.java, src/main/java/com/festival/domain/booth/repository/BoothRepositoryCustom.java, src/main/java/com/festival/domain/booth/repository/BoothRepositoryImpl.java, src/main/java/com/festival/domain/booth/service/BoothService.java, src/main/java/com/festival/domain/guide/controller/GuideController.java, src/main/java/com/festival/domain/guide/dto/GuideReq.java, src/main/java/com/festival/domain/guide/dto/GuideRequest.java, src/main/java/com/festival/domain/guide/dto/GuideRes.java, src/main/java/com/festival/domain/guide/dto/GuideResponse.java, src/main/java/com/festival/domain/guide/model/Guide.java, src/main/java/com/festival/domain/guide/model/GuideStatus.java, src/main/java/com/festival/domain/guide/model/GuideType.java, src/main/java/com/festival/domain/guide/repository/GuideRepository.java, src/main/java/com/festival/domain/guide/repository/GuideRepositoryCustom.java, src/main/java/com/festival/domain/guide/repository/GuideRepositoryImpl.java, src/main/java/com/festival/domain/guide/repository/vo/GuideSearchCond.java, src/main/java/com/festival/domain/guide/service/GuideService.java, src/main/java/com/festival/domain/program/controller/ProgramController.java, src/main/java/com/festival/domain/timetable/controller/TimeTableController.java
- #105 
- 안내사항의 기본적인 CRUD 기능을 구현했습니다.
<hr>
<br>
=> [#105] 안내사항 도메인의 CRUD 기능을 구현한다.

src/main/java/com/festival/common/util/ValidationUtils.java, src/main/java/com/festival/domain/bambooforest/controller/BambooForestController.java, src/main/java/com/festival/domain/booth/controller/BoothController.java, src/main/java/com/festival/domain/guide/controller/GuideController.java, src/main/java/com/festival/domain/guide/model/GuideStatus.java, src/main/java/com/festival/domain/guide/model/GuideType.java, src/main/java/com/festival/domain/program/controller/ProgramController.java, src/main/java/com/festival/domain/timetable/controller/TimeTableController.java, src/main/java/com/festival/domain/timetable/dto/TimeTableCreateReq.java
- #109 
- BambooForest, Timetable, Booth, Program, Guide 에 대한 입력값 유효성 체크를 진행합니다.
=> [#109] Validation utils 유효성 체크 로직 추가

src/main/java/com/festival/domain/guide/controller/GuideController.java, src/main/java/com/festival/domain/guide/dto/GuideReq.java, src/main/java/com/festival/domain/guide/dto/GuideRes.java, src/main/java/com/festival/domain/guide/model/Guide.java, src/main/java/com/festival/domain/guide/repository/GuideRepositoryCustom.java, src/main/java/com/festival/domain/guide/repository/GuideRepositoryImpl.java, src/main/java/com/festival/domain/guide/service/GuideService.java, src/main/java/com/festival/domain/program/dto/ProgramReq.java, src/main/java/com/festival/domain/program/dto/ProgramRes.java, src/main/java/com/festival/domain/program/model/Program.java, src/main/java/com/festival/domain/program/repository/ProgramRepositoryCustom.java, src/main/java/com/festival/domain/program/repository/ProgramRepositoryCustomImpl.java, src/main/java/com/festival/domain/program/service/ProgramService.java
- #114 
- 축제 프로그램과 축제 가이드에 대한 이미지 업로드 로직을 작성했습니다.
- Guide작성 중 getList의 API스펙을 맞추기 위해 Page -> LIst로 변경했씁니다.
=> [#114] 축제 프로그램, 가이드 이미지 업로드 로직 작성

build.gradle, src/main/java/com/festival/common/infra/s3bucket/S3BucketConfig.java, src/main/java/com/festival/common/util/ImageUtils.java, src/main/java/com/festival/domain/guide/controller/GuideController.java, src/main/java/com/festival/domain/guide/dto/GuideReq.java, src/main/java/com/festival/domain/guide/dto/GuideRes.java, src/main/java/com/festival/domain/guide/model/Guide.java, src/main/java/com/festival/domain/guide/repository/GuideRepositoryCustom.java, src/main/java/com/festival/domain/guide/repository/GuideRepositoryImpl.java, src/main/java/com/festival/domain/guide/service/GuideService.java, src/main/java/com/festival/domain/image/service/ImageService.java, src/main/java/com/festival/domain/program/dto/ProgramReq.java, src/main/java/com/festival/domain/program/dto/ProgramRes.java, src/main/java/com/festival/domain/program/model/Program.java, src/main/java/com/festival/domain/program/repository/ProgramRepositoryCustom.java, src/main/java/com/festival/domain/program/repository/ProgramRepositoryCustomImpl.java, src/main/java/com/festival/domain/program/service/ProgramService.java
- #114 
- 겹치는 부분 없을 것 같아서 일단 추가 작업 진행했습니다. 충돌 나면 제가 해결할게요!
- S3버킷에 이미지 업로드를 하게됩니다! 
- secret.yml추가하셔야 합니다. 노션에 올려둘게요
- 실제 이미지 올라가는 건 확인을 해서 테스트 전용 api를 만들고 설정해두었습니다.
=> [#117] 이미지 업로드 S3 Bucket 연동

src/main/java/com/festival/common/exception/ControllerAdvice.java, src/main/java/com/festival/common/exception/CustomException.java, src/main/java/com/festival/common/exception/ErrorCode.java, src/main/java/com/festival/common/exception/GlobalExceptionHandler.java, src/main/java/com/festival/common/exception/custom_exception/DuplicationException.java, src/main/java/com/festival/common/exception/custom_exception/ForbiddenException.java, src/main/java/com/festival/common/exception/custom_exception/InvalidException.java, src/main/java/com/festival/common/exception/custom_exception/NotFoundException.java, src/main/java/com/festival/common/util/ImageUtils.java, src/main/java/com/festival/common/util/Utill.java, src/main/java/com/festival/domain/bambooforest/controller/BambooForestController.java, src/main/java/com/festival/domain/bambooforest/service/BamBooForestService.java, src/main/java/com/festival/domain/booth/controller/BoothController.java, src/main/java/com/festival/domain/booth/controller/dto/BoothReq.java, src/main/java/com/festival/domain/booth/model/Booth.java, src/main/java/com/festival/domain/booth/service/BoothService.java, src/main/java/com/festival/domain/guide/controller/GuideController.java, src/main/java/com/festival/domain/guide/service/GuideService.java, src/main/java/com/festival/domain/image/service/ImageService.java, src/main/java/com/festival/domain/member/controller/MemberController.java, src/main/java/com/festival/domain/member/service/MemberService.java, src/main/java/com/festival/domain/program/controller/ProgramController.java, src/main/java/com/festival/domain/program/model/Program.java, src/main/java/com/festival/domain/program/service/ProgramService.java, src/main/java/com/festival/domain/timetable/controller/TimeTableController.java, src/main/java/com/festival/domain/timetable/model/TimeTable.java, src/main/java/com/festival/domain/timetable/service/TimeTableService.java
- #121 
- 예외 공통 처리 로직을 작성했습니다.
- NotFoundException과 같이 공통되는 예외는 묶어주고 ErrorCode로 구분합니다.
- 위와 같은 예외는 다시 CustomException으로 묶어 GlobalHandler에서 공통으로 캐치합니다. 
=> [#121] 예외 공통 처리 로직 작성

src/main/java/com/festival/common/exception/ErrorCode.java, src/main/java/com/festival/common/exception/custom_exception/AlreadyDeleteException.java, src/main/java/com/festival/common/exception/custom_exception/BadRequestException.java, src/main/java/com/festival/common/exception/custom_exception/NotFoundException.java, src/main/java/com/festival/common/security/CustomUserDetailsService.java, src/main/java/com/festival/common/security/dto/MemberLoginReq.java, src/main/java/com/festival/common/util/AuditingConfig.java, src/main/java/com/festival/common/util/ValidationUtils.java, src/main/java/com/festival/domain/bambooforest/service/BamBooForestService.java, src/main/java/com/festival/domain/booth/service/BoothService.java, src/main/java/com/festival/domain/guide/controller/GuideController.java, src/main/java/com/festival/domain/guide/dto/GuideReq.java, src/main/java/com/festival/domain/guide/model/Guide.java, src/main/java/com/festival/domain/guide/model/GuideType.java, src/main/java/com/festival/domain/guide/service/GuideService.java, src/main/java/com/festival/domain/image/service/ImageService.java, src/main/java/com/festival/domain/member/dto/MemberJoinReq.java, src/main/java/com/festival/domain/member/model/AuthDetailsEntity.java, src/main/java/com/festival/domain/member/model/Member.java, src/main/java/com/festival/domain/member/repository/MemberRepository.java, src/main/java/com/festival/domain/member/service/MemberService.java, src/test/java/com/festival/domain/bambooforest/controller/BambooForestControllerTest.java, src/test/java/com/festival/domain/bambooforest/service/BamBooForestServiceTest.java, src/test/java/com/festival/domain/guide/controller/GuideControllerTest.java, src/test/java/com/festival/domain/member/fixture/MemberFixture.java, src/test/java/com/festival/domain/util/ControllerTestSupport.java, src/test/java/com/festival/domain/util/TestImageUtils.java
- #128  
- 안내사항 통합 테스트 로직을 구현했습니다.
- 멤버 인증 방식을 간이로 수정하였습니다.
=> [#128] 안내사항 통합테스트 로직을 구현한다. (1)

src/main/java/com/festival/common/util/ImageUtils.java, src/main/java/com/festival/domain/guide/model/Guide.java, src/main/java/com/festival/domain/guide/repository/GuideRepositoryCustom.java, src/main/java/com/festival/domain/guide/repository/GuideRepositoryImpl.java, src/main/java/com/festival/domain/guide/service/GuideService.java, src/main/java/com/festival/domain/image/service/ImageService.java, src/test/java/com/festival/domain/guide/controller/GuideControllerTest.java
- #128  
- 안내사항 서비스 로직을 수정하였습니다.
- S3 삭제로직을 추가하였습니다.
=> [#128] 안내사항 통합테스트 로직을 구현한다.

src/main/java/com/festival/common/exception/ErrorCode.java, src/main/java/com/festival/common/exception/ErrorResponse.java, src/main/java/com/festival/common/exception/GlobalExceptionHandler.java
- #141 
- RestControllerAdvice를 이용해 CustomException에 대해 공통 처리 하였습니다.
=> [#141] CustomException 공통 처리

src/main/java/com/festival/common/util/ValidationUtils.java, src/main/java/com/festival/domain/timetable/controller/TimeTableController.java, src/main/java/com/festival/domain/timetable/dto/TimeTableReq.java, src/main/java/com/festival/domain/timetable/model/TimeTable.java, src/main/java/com/festival/domain/timetable/service/TimeTableService.java, src/test/java/com/festival/domain/bambooforest/service/BamBooForestServiceTest.java, src/test/java/com/festival/domain/member/fixture/MemberFixture.java, src/test/java/com/festival/domain/program/service/ProgramServiceTest.java, src/test/java/com/festival/domain/timetable/fixture/TimeTableFixture.java, src/test/java/com/festival/domain/timetable/service/TimeTableServiceTest.java
- #143 
- Fixture라는게 변하면 안되는 객체인데 수정될 수 있는 테스트에서 활용하고 있었습니다.
- 계속해서 사용해야 하는 객체를 수정하면서 이후 테스트에도 영향을 주는 문제가 발생해서 로직을 수정했습니다.
- 수정될 수 있는 객체에 대해서는 공통메서드로 뽑아내고 고정된 객체에 한에서만 전역변수로 만들어 사용합니다. 
**확인하시고 리뷰해주시면 감사하겠습니다.**
=> [#143] 타임테이블 서비스 계층 단위 테스트 작성

src/main/java/com/festival/common/util/ValidationUtils.java, src/main/java/com/festival/domain/bambooforest/controller/BambooForestController.java, src/main/java/com/festival/domain/bambooforest/dto/BamBooForestReq.java, src/main/java/com/festival/domain/bambooforest/model/BamBooForest.java, src/main/java/com/festival/domain/bambooforest/service/BamBooForestService.java, src/test/java/com/festival/domain/bambooforest/controller/BambooForestControllerTest.java, src/test/java/com/festival/domain/bambooforest/fixture/BamBooForestFixture.java, src/test/java/com/festival/domain/bambooforest/service/BamBooForestServiceTest.java
- #148 
- fixture 사용법 변경에 의한 수정 작업 진행했습니다.
**확인하시고 리뷰해주시면 감사하겠습니다.**
=> [#148] 대나무숲 서비스 계층 단위 테스트 수정

src/main/java/com/festival/domain/booth/service/BoothService.java, src/test/java/com/festival/domain/booth/fixture/BoothFixture.java, src/test/java/com/festival/domain/booth/service/BoothServiceTest.java
- #152 
- 축제 부스 통합 테스트 로직을 구현하였습니다.
- 
**확인하시고 리뷰해주시면 감사하겠습니다.**
=> [#152] 축제 부스 서비스 단위테스트 수정

src/main/java/com/festival/domain/program/controller/ProgramController.java, src/main/java/com/festival/domain/program/service/ProgramService.java, src/test/java/com/festival/domain/program/fixture/ProgramFixture.java, src/test/java/com/festival/domain/program/service/ProgramServiceTest.java
- #155 
- 축제 프로그램 통합 테스트 로직을 구현하였습니다.
- 
**확인하시고 리뷰해주시면 감사하겠습니다.**
=> [#155] 축제 프로그램 서비스 단위 테스트 수정

src/main/java/com/festival/domain/guide/service/GuideService.java, src/test/java/com/festival/domain/guide/fixture/GuideFixture.java, src/test/java/com/festival/domain/guide/service/GuideServiceTest.java
- #158 
- 축제 가이드 서비스 단위 테스트를 작성하였습니다.
- 
**확인하시고 리뷰 해주시면 감사하겠습니다.**
=> [#158] 축제 가이드 서비스 단 단위 테스트 작성

src/test/java/com/festival/domain/booth/service/BoothServiceTest.java, src/test/java/com/festival/domain/guide/controller/GuideControllerTest.java, src/test/java/com/festival/domain/guide/service/GuideServiceTest.java, src/test/java/com/festival/domain/image/fixture/ImageFixture.java
- #160 
- 이미지 고정 객체의 변수 명을 수정했습니다.
**확인하시고 리뷰 해주시면 감사하겠습니다.**
=> [#160] ImageFixture 변수 명 수정 

src/main/java/com/festival/domain/bambooforest/controller/BambooForestController.java, src/main/java/com/festival/domain/timetable/controller/TimeTableController.java
- #166 
- 대나무숲의 삭제 권한은 ADMIN만 허용한다.
- 시간표의 CUD 권한은 ADMIN만 허용한다.
=> [#166] 대나무숲, 시간표 도메인의 권한은 ADMIN으로 한정한다.

src/test/java/com/festival/domain/bambooforest/controller/BambooForestIntegrationTest.java, src/test/java/com/festival/domain/booth/controller/BoothIntegrationTest.java, src/test/java/com/festival/domain/guide/controller/GuideIntegrationTest.java, src/test/java/com/festival/domain/program/controller/ProgramIntegrationTest.java, src/test/java/com/festival/domain/timetable/controller/TimeTableIntegrationTest.java
- #171 
- 회의를 통해 정했던 페이징 값으로 통합테스트 내부로직의 Pageable 값을 변경하였습니다.
- 기존 ControllerTest로 설정되어있던 클래스 명이 오해를 부를 수 있을 것같아, IntegrationTest로 이름을 수정하였습니다.
=> [#171] 통합테스트 페이징 개수 조절

build.gradle, src/main/java/com/festival/common/redis/RedisConfig.java, src/main/java/com/festival/domain/booth/controller/BoothController.java, src/main/java/com/festival/domain/booth/service/BoothService.java, src/main/java/com/festival/domain/guide/controller/GuideController.java, src/main/java/com/festival/domain/guide/model/Guide.java, src/main/java/com/festival/domain/guide/service/GuideService.java, src/test/java/com/festival/domain/booth/service/BoothServiceTest.java, src/test/java/com/festival/domain/guide/service/GuideServiceTest.java
- #174 
- 메인 페이지에서 표시될 인기순 게시물을 위해
- 각 게시물별 조회수 선언, 증감 로직을 구현하였습니다.
=> [#174] 조회수 증감 로직을 구현한다.(V1)

src/main/java/com/festival/common/redis/RedisConfig.java, src/main/java/com/festival/common/redis/RedisService.java, src/main/java/com/festival/common/scheduler/SchedulerConfig.java, src/main/java/com/festival/common/scheduler/SchedulerRunner.java, src/main/java/com/festival/domain/guide/model/Guide.java, src/main/java/com/festival/domain/guide/service/GuideService.java
- #176 
- 안내사항 도메인의 우선적으로 조회수 로직을 적용한 것을 리팩토링 하였습니다.
- 의존성을 나누어 진행하는 식으로 스케줄링이 동작되도록 수정하였습니다.
**코드를 확인하시고 궁금한 점이나, 보안할 사항이 있으시다면 리뷰 부탁드립니다.**
=> [#176] 안내사항 조회수 로직 리팩토링

src/main/java/com/festival/common/redis/RedisService.java, src/main/java/com/festival/domain/booth/service/BoothService.java, src/main/java/com/festival/domain/guide/service/GuideService.java, src/main/java/com/festival/domain/program/service/ProgramService.java
- #176 
- 구분성을 위해 setKey 값을 DomainName으로 수정하였습니다.
=> [#176] 스케줄러 다른 도메인 로직 적용

src/main/java/com/festival/domain/timetable/dto/TimeTableDateReq.java
- #185 
- TimeTableDateReq의 미사용 필드 offset을 삭제합니다.
=> [#185] 시간표 dto 미사용 필드 삭제

.github/workflows/work.yml
- CICD를 적용하기 위해 실험적으로 github Actions를 적용합니다.
- 과정을 테스트 해봅니다.
=> feature/Create work.yml

Dockerfile
=> feature/Create Dockerfile

build.gradle, src/main/resources/application.yml
- #211 
- 0.0.1로 고정되는 버전을 옵션에따라 상승하도록 수정합니다.
=> [#211] 스프링부트 프로젝트의 버전을 명령어에 따라 자동으로 상승되도록 한다.

src/main/java/com/festival/common/swagger/SwaggerConfig.java, src/main/java/com/festival/domain/booth/controller/BoothController.java, src/main/java/com/festival/domain/guide/controller/GuideController.java, src/main/java/com/festival/domain/member/controller/MemberController.java, src/main/java/com/festival/domain/program/controller/ProgramController.java, src/main/java/com/festival/domain/timetable/controller/TimeTableController.java
=> [#231] swagger api 연동하기 v2

src/main/java/com/festival/common/security/config/SecurityConfig.java
=> [#235] security config 이동 및 preAuthorized 관련 어노테이션 추가

src/main/java/com/festival/domain/booth/controller/BoothController.java, src/main/java/com/festival/domain/guide/controller/GuideController.java, src/main/java/com/festival/domain/program/controller/ProgramController.java, src/main/java/com/festival/domain/timetable/controller/TimeTableController.java
- #238
- 각 컨트롤러 별 헤더 적용 범위를 수정했습니다.
- 컨트롤러 어노테이션이 아닌, 메소드 단위의 어노테이션에 옵션을 적용하도록 수정하였습니다.
=> [#238] swagger header적용범위 수정 

src/main/java/com/festival/domain/bambooforest/controller/BambooForestController.java, src/main/java/com/festival/domain/booth/controller/BoothController.java, src/main/java/com/festival/domain/guide/controller/GuideController.java, src/main/java/com/festival/domain/program/controller/ProgramController.java, src/main/java/com/festival/domain/timetable/controller/TimeTableController.java, src/test/java/com/festival/domain/bambooforest/controller/BambooForestIntegrationTest.java, src/test/java/com/festival/domain/booth/controller/BoothIntegrationTest.java, src/test/java/com/festival/domain/guide/controller/GuideIntegrationTest.java, src/test/java/com/festival/domain/program/controller/ProgramIntegrationTest.java
- #240 
- 권한 설정 ADMIN -> ROLE_ADMIN
- hasRole or로 구분하기
=> [#240] 테스트 버그 수정

src/main/java/com/festival/domain/program/controller/ProgramController.java
- #240 
- @PreAuthorize("hasRole('ROLE_ADMIN') or  hasRole('ROLE_MANAGER' **`}`** )")
- 위 코드에서 오른쪽 끝 부분에 `}`와 같은 오타가 있었습니다.
- 컨트롤러 단에서 해당 오류들을 수정하였습니다.
- **@PreAuthorize("hasRole('ROLE_ADMIN') or  hasRole('ROLE_MANAGER')")**
=> [#240] 컨트롤러 권한 설정 괄호 수정

src/main/java/com/festival/common/security/JwtTokenProvider.java, src/main/java/com/festival/domain/bambooforest/controller/BambooForestController.java, src/main/java/com/festival/domain/booth/controller/BoothController.java, src/main/java/com/festival/domain/guide/controller/GuideController.java, src/main/java/com/festival/domain/member/model/MemberRole.java, src/main/java/com/festival/domain/program/controller/ProgramController.java, src/main/java/com/festival/domain/timetable/controller/TimeTableController.java
- #249 
- @PreAuthorize("hasRole('ADMIN')   -> "ROLE_ADMIN" 체킹
- @PreAuthorize("hasAuthority('ADMIN')    -> "ADMIN" 체킹
- 기존 테스트가 터졌던건 hasAuthority가 ADMIN을 체크하는데    
@WithMockUser(username = "testUser", roles = "ADMIN") 가 ROLE_ADMIN으로 값을 넣어줬기 때문입니다.
- "hasRole('ADMIN')"의 형태로 전부 변경했습니다
- JWT를 생성할 때 roles를 그대로 넣는 과정에서 [user] 와 같은 형태로 들어가고있었습니다.
권한 정보를 세팅할 때 ","로 split하고 있지만 결국 [user]의 형태로 설정이 됩니다.
- 두 가지 문제로 ROLE_USER의 형태가 아닌것과 리스트를 그대로 반환하고 있는 것입니다.
-> MemberRole의 value를 ROLE_ADMIN, ROLE_MANAGER로 변경했습니다.
-> list를 ","로 joining했습니다.
=> [#249] JWT권한 검증 버그 수정

src/main/java/com/festival/domain/bambooforest/controller/BambooForestController.java, src/main/java/com/festival/domain/bambooforest/dto/BamBooForestListReq.java, src/main/java/com/festival/domain/booth/controller/BoothController.java, src/main/java/com/festival/domain/booth/controller/dto/BoothListReq.java, src/main/java/com/festival/domain/booth/service/BoothService.java, src/main/java/com/festival/domain/guide/controller/GuideController.java, src/main/java/com/festival/domain/guide/dto/GuideListReq.java, src/main/java/com/festival/domain/guide/service/GuideService.java, src/main/java/com/festival/domain/program/controller/ProgramController.java, src/main/java/com/festival/domain/program/dto/ProgramListReq.java, src/main/java/com/festival/domain/program/service/ProgramService.java, src/main/java/com/festival/domain/timetable/controller/TimeTableController.java, src/test/java/com/festival/domain/booth/service/BoothServiceTest.java
- #244 
- 기존 @ModelAttribute를 이용하던 방식에서 @RequestBody로 통합했습니다.
- 이미지를 받는 요청만 MultiPartFormData로 받습니다
- 각 클래스 별 띄어쓰기, 미사용 의존성 제거를 수행했습니다.
=> [#253] ContentType스타일 통합

src/main/java/com/festival/domain/program/dto/ProgramRes.java, src/test/java/com/festival/domain/program/controller/ProgramIntegrationTest.java, src/test/java/com/festival/domain/program/fixture/ProgramFixture.java, src/test/java/com/festival/domain/program/service/ProgramServiceTest.java
- #266 
- 전체 리팩토링 작업이 있었습니다.
- 이후 테스트를 돌려보았을때 많은 오류가 발생하여
- 프로그램 도메인의 테스트 코드를 수정하였습니다.
=> [#266] 리팩토링 작업으로 인한 프로그램 도메인 테스트 로직 수정

src/main/java/com/festival/domain/timetable/controller/TimeTableController.java, src/test/java/com/festival/domain/program/controller/ProgramIntegrationTest.java, src/test/java/com/festival/domain/timetable/controller/TimeTableIntegrationTest.java, src/test/java/com/festival/domain/timetable/fixture/TimeTableFixture.java, src/test/java/com/festival/domain/timetable/service/TimeTableServiceTest.java
- #268
- 전체 리팩토링 작업이 있었습니다.
- 이후 테스트를 돌려보았을때 많은 오류가 발생하여
- 시간표 도메인의 테스트 코드를 수정하였습니다.
=> [#268] test: 리팩토링으로 인한 테스트코드 수정(TimeTable)

src/main/java/com/festival/common/util/ValidationUtils.java, src/main/java/com/festival/domain/guide/controller/GuideController.java, src/main/java/com/festival/domain/guide/dto/GuideListReq.java, src/main/java/com/festival/domain/guide/dto/GuidePageRes.java, src/main/java/com/festival/domain/guide/dto/GuideReq.java, src/main/java/com/festival/domain/guide/dto/GuideRes.java, src/main/java/com/festival/domain/guide/model/Guide.java, src/main/java/com/festival/domain/guide/service/GuideService.java, src/test/java/com/festival/domain/guide/controller/GuideIntegrationTest.java, src/test/java/com/festival/domain/guide/fixture/GuideFixture.java, src/test/java/com/festival/domain/guide/service/GuideServiceTest.java
- #270 
- 전체 리팩토링 작업이 있었습니다.
- 이후 테스트를 돌려보았을때 많은 오류가 발생하여
- 안내사항 도메인의 테스트 코드를 수정하였습니다.
=> [#270] 안내사항 도메인 테스트 코드 수정

src/main/java/com/festival/common/util/ValidationUtils.java, src/main/java/com/festival/domain/booth/controller/BoothController.java
- #277
- validationUtils 클래스에서 날짜 패턴에 오류가 발생했습니다.
- 해당 부분을 수정하였습니다.
=> [#277] 시간 검증 코드 수정

src/main/java/com/festival/common/util/ValidationUtils.java, src/main/java/com/festival/domain/bambooforest/controller/BambooForestController.java, src/main/java/com/festival/domain/bambooforest/repository/impl/BamBooForestRepositoryImpl.java, src/main/java/com/festival/domain/booth/repository/impl/BoothRepositoryImpl.java, src/main/java/com/festival/domain/guide/repository/impl/GuideRepositoryImpl.java, src/main/java/com/festival/domain/program/repository/impl/ProgramRepositoryCustomImpl.java, src/main/java/com/festival/domain/timetable/repository/impl/TimeTableRepositoryImpl.java
- #277
- validationUtils 클래스에서 이메일이 입력되지 않았는데도 검증을시도하고 있었습니다.
- 선택이기에 입력되었을 경우에만 되도록 수정합니다.
=> [#277] 쿼리 조회시에 삭제객체 조회X

src/main/java/com/festival/domain/booth/service/BoothService.java, src/main/java/com/festival/domain/guide/service/GuideService.java
- #282 
- 단건 조회시에 삭제되었는지 확인을 안하고 있었습니다.
- 해당 로직을 수정했습니다.
=> [#282] 쿼리 단건 조회 로직 수정

build.gradle, src/main/resources/application.yml
- #288 
- build.gradle의 version이 수정되지 않는 문제가 있었습니다.
- version = '0.0.1-SNAPSHOT' -> 0.0.1로 고정
- 파일의 코드를 수정하는 코드를 추가하여 해당 부분을 해결하였습니다.
- **def gradleFile = file('build.gradle')
gradleFile.text = gradleFile.text.replace("version = '${project.version}'", "version = '$newVersion-SNAPSHOT'")**
<br>
=> [#288] build.gradle 버전 업데이트 코드 추가

.github/workflows/work.yml
=> 릴리즈 노트 생성 테스트 2

README.md
=> [#noissue] ReadMe.md 업데이트

src/main/java/com/festival/domain/booth/controller/dto/BoothReq.java, src/main/java/com/festival/domain/booth/model/Booth.java, src/main/java/com/festival/domain/guide/dto/GuideReq.java, src/main/java/com/festival/domain/program/dto/ProgramListReq.java, src/main/java/com/festival/domain/program/dto/ProgramReq.java, src/main/java/com/festival/domain/timetable/dto/TimeTableDateReq.java, src/main/java/com/festival/domain/timetable/dto/TimeTableReq.java
- #321 
- 프로그램 파라미터명이 오기입 되어있던 필드들의 이름을 수정하였습니다.
- startTime -> startDate, endTime -> endTime
=> [#321] 프로그램 파라미터명 변경 

src/main/java/com/festival/domain/guide/dto/GuideRes.java
- #332 
- 클라이언트에서 가이드 작성자를 구분하기 위한 username 컬럼을 추가했습니다.
=> [#332] 가이드 응답 스펙에 username을 추가합니다.

src/main/java/com/festival/common/security/JwtTokenProvider.java, src/main/java/com/festival/domain/member/controller/MemberController.java, src/main/java/com/festival/domain/member/service/MemberService.java
=> [#343] 재발급 요청 시 토큰의 로그아웃 여부를 체크합니다.

src/main/java/com/festival/domain/guide/dto/GuideRes.java
- #345 
- 안내사항 도메인의 생성 시간이 필요하여, 해당 필드를 추가합니다.
=> [#345] 안내사항 등록시간 응답 추가

.github/workflows/work.yml
=> [#noissue] 배포 포트주소 변경

src/main/java/com/festival/common/security/config/SecurityConfig.java
- securityConfig OPTIONS 요청 허용
=> [#noissue] refactor: OPTIONS 요청 허용
