src/main/java/com/festival/domain/info/festivalEvent/controller/FestivalEventController.java, src/main/java/com/festival/domain/info/festivalEvent/data/dto/FestivalEventRes.java, src/main/java/com/festival/domain/info/festivalEvent/data/entity/FestivalEvent.java, src/main/java/com/festival/domain/info/festivalEvent/repository/FestivalEventRepository.java, src/main/java/com/festival/domain/info/festivalEvent/service/FestivalEventService.java, src/main/java/com/festival/initData/NotProd.java
- 축제 이벤트 단일 조회 API를 작성합니다.
- 축제 이벤트 전체 조회 API를 작성합니다.
- Paging처리
- initData추가 어드민계정 생성
=> 축제 이벤트 단일, 전체 조회API 

src/main/java/com/festival/domain/admin/data/entity/Admin.java, src/main/java/com/festival/domain/fleaMarket/data/entity/FleaMarket.java, src/main/java/com/festival/domain/fleaMarket/data/entity/FleaMarketImage.java, src/main/java/com/festival/domain/info/festivalPub/data/entity/file/PubImage.java, src/main/java/com/festival/domain/info/festivalPub/data/entity/pub/Pub.java, src/main/java/com/festival/domain/info/festivalPub/service/PubService.java
- 현재 주점 엔티티에는 주인 엔티티가 아님에도 불구하고 이미지 엔티티의 외래키를 매핑하고 있었던 겁니다. 주인 엔티티가 아닐 경우 외래키를 가지고 있어선 안됩니다.
- 따라서 PubImage의 pub 객체를 주인으로 정하여 PubImage에 외래키를 저장하게 하고, 주점 엔티티에서 PubImage에 저장되던 pub에 매핑되도록 수정하였습니다.
=> refactor: 연관관계 수정 (#53)

src/main/java/com/festival/domain/admin/data/entity/Admin.java, src/main/java/com/festival/domain/info/festivalPub/data/entity/pub/Pub.java
- 현재 adminId로 getPubs를 찾는 일이 없고, querydsl로 pub의 쿼리를 생성하여 adminId를 찾아서 Page를 반환하는 작업을 하고 있습니다.
- 이 경우 Pub에 admin이 단방향으로 이미 연관관계가 설정되어 있기 때문에, 굳이 사용하는 로직이 있지 않다면 단방향으로만 구성하여도 괜찮다고 합니다. 따라서 아직 Admin 엔티티에 pubs 변수를 사용하는 일이 없기 때문에 단방향으로만 연관관계를 설정해보고 테스트 해보려 합니다.
=> refactor: 연관관계 설정 단방향으로 변경 (#60)

src/main/java/com/festival/common/base/BaseEntity.java, src/main/java/com/festival/domain/timetable/controller/TimeTableController.java, src/main/java/com/festival/domain/timetable/dto/TimeTableCreateReq.java, src/main/java/com/festival/domain/timetable/dto/TimeTableDateReq.java, src/main/java/com/festival/domain/timetable/dto/TimeTableDto.java, src/main/java/com/festival/domain/timetable/dto/TimeTableRes.java, src/main/java/com/festival/domain/timetable/dto/TimeTableSearchCond.java, src/main/java/com/festival/domain/timetable/model/TImeTable.java, src/main/java/com/festival/domain/timetable/model/TimeTable.java, src/main/java/com/festival/domain/timetable/model/TimeTableStatus.java, src/main/java/com/festival/domain/timetable/repository/TimeTableRepository.java, src/main/java/com/festival/domain/timetable/repository/TimeTableRepositoryCustom.java, src/main/java/com/festival/domain/timetable/repository/impl/TimeTableRepositoryImpl.java, src/main/java/com/festival/domain/timetable/service/TimeTableService.java, src/main/java/com/festival/old/domain/fleaMarket/repository/FleaMarketRepositoryImpl.java, src/main/java/com/festival/old/domain/foodTruck/repository/impl/FoodTruckRepositoryCustomImpl.java
- #95 
- 시간표 도메인의 기본적인 CRUD 기능을 구현했습니다.
- 시간표 도메인의 상태 확인을 위한 TimeTableStatus 클래스를 구현했습니다.
- 시간과 생성, 수정자의 공통 로직을 담당하는 BaseEntity를 구현하였습니다.
<hr>
<br>
=> [#95] 시간표 도메인의 CRUD 기능을 구현한다.

src/main/java/com/festival/domain/bambooforest/controller/BambooForestController.java, src/main/java/com/festival/domain/bambooforest/dto/BamBooForestCreateReq.java, src/main/java/com/festival/domain/bambooforest/dto/BamBooForestRes.java, src/main/java/com/festival/domain/bambooforest/dto/BambooForestDto.java, src/main/java/com/festival/domain/bambooforest/model/BamBooForest.java, src/main/java/com/festival/domain/bambooforest/model/BamBooForestStatus.java, src/main/java/com/festival/domain/bambooforest/model/BambooForest.java, src/main/java/com/festival/domain/bambooforest/repository/BamBooForestRepository.java, src/main/java/com/festival/domain/bambooforest/repository/BamBooForestRepositoryCustom.java, src/main/java/com/festival/domain/bambooforest/repository/impl/BamBooForestRepositoryImpl.java, src/main/java/com/festival/domain/bambooforest/service/BamBooForestService.java, src/main/java/com/festival/domain/bambooforest/service/vo/BamBooForestSearchCond.java
- #98 
- 대나무 숲  도메인의 기본적인 CRUD 기능을 구현했습니다.
- 대나무 숲 도메인의 상태 확인을 위한 BamBooForestStatus 클래스를 구현했습니다.
<hr>
<br>
=> [#98] 대나무 숲 도메인의 CRUD 기능을 구현한다.

src/main/java/com/festival/domain/timetable/dto/TimeTableSearchCond.java, src/main/java/com/festival/domain/timetable/repository/TimeTableRepositoryCustom.java, src/main/java/com/festival/domain/timetable/repository/impl/TimeTableRepositoryImpl.java, src/main/java/com/festival/domain/timetable/service/TimeTableService.java
- #102 
- 현재 시간표 조회에서는 Paging이 아닌 List로 조회하는 중입니다.
- 따라서 Paging 처리로직을 제거하였습니다.
<hr>
<br>
=> [#102] TimeTable 조회시에 Paging 처리 제거

src/main/java/com/festival/common/security/SecurityConfig.java, src/main/java/com/festival/domain/member/controller/MemberController.java, src/main/java/com/festival/domain/member/dto/MemberDto.java, src/main/java/com/festival/domain/member/dto/MemberReq.java, src/main/java/com/festival/domain/member/model/Member.java, src/main/java/com/festival/domain/member/model/MemberRole.java, src/main/java/com/festival/domain/member/repository/MemberRepository.java, src/main/java/com/festival/domain/member/service/MemberService.java
- #107 
- 전체적인 Member 도메인의 CRUD 로직을 구현하였습니다.
- 권한을 위한 MemberRole 클래스도 생성했습니다.
- 우선은 세션을 통한 시큐리티 설정만 해두었습니다. 이후에 JWT를 사용하여 인증하는식으로 변경할 예정입니다.
=> [#107] 멤버 도메인의 기본적인 CRUD로직을 구현한다.

src/test/java/com/festival/ControllerTestSupport.java, src/test/java/com/festival/domain/bambooforest/controller/BambooForestControllerTest.java
- #124  
- 테스트 지원 클래스의 타입을 추상화로 변경하였습니다.
- 대나무숲 게시물 삭제 테스트 케이스의 값 확인 로직을 추가하였습니다.
- 대나무숲 게시물 목록 조회 케이스의 사이즈 확인 로직을 추가하였습니다.
=> [#124] 대나무숲 테스트 케이스 수정

src/main/java/com/festival/common/data/Data.java, src/main/java/com/festival/common/security/JwtTokenProvider.java, src/main/java/com/festival/common/util/AuditingConfig.java
- #124  
- 로그인을 위한 더미 데이터를 추가했습니다. 추후에 .sql 파일로 대체하면 좋을 것 같습니다.
- @CreatedBy와 @UpdatedBy가 동작하지 않는 것을 확인하고 수정했습니다.
-> AuditingConfig에서 AuditorAware<String>을 빈으로 등록해주었습니다.
=> [#129] 엔티티 생성, 수정 시 담당자 업데이트

src/test/java/com/festival/domain/bambooforest/fixture/BamBooForestFixture.java, src/test/java/com/festival/domain/bambooforest/service/BamBooForestServiceTest.java, src/test/java/com/festival/domain/member/fixture/MemberFixture.java
- #131 
- 대나무숲 서비스 계층의 단위 테스트를 작성했습니다.
- 생성, 삭제에 대한 테스트를 작성했습니다.
- 리스트 조회는 회의 이후 작성하겠습니다.
- 권한 검사를 위한 MemberFixture를 따로 생성해두었습니다.
=> [#131] 대나무숲 서비스 단위 테스트 작성

src/test/java/com/festival/domain/bambooforest/controller/BambooForestControllerTest.java, src/test/java/com/festival/domain/bambooforest/service/BamBooForestServiceTest.java, src/test/java/com/festival/domain/booth/service/BoothServiceTest.java, src/test/java/com/festival/domain/guide/controller/GuideControllerTest.java
- #124
- #128 
- 권한 분리, 상태값 로직 변경 및 이동에 따른 예외사항 테스트케이스를 추가하였습니다.
=> [#124, #128] 대나무숲, 안내사항 통합테스트 케이스 추가

src/main/java/com/festival/domain/booth/controller/BoothController.java, src/main/java/com/festival/domain/booth/controller/dto/BoothReq.java, src/main/java/com/festival/domain/booth/model/Booth.java, src/main/java/com/festival/domain/booth/model/BoothType.java, src/main/java/com/festival/domain/guide/dto/GuideReq.java, src/test/java/com/festival/domain/bambooforest/controller/BambooForestControllerTest.java, src/test/java/com/festival/domain/booth/controller/BoothControllerTest.java, src/test/java/com/festival/domain/guide/controller/GuideControllerTest.java, src/test/java/com/festival/domain/util/ControllerTestSupport.java
- #145 
- 축제부스 통합 테스트 로직을 구현하였습니다.
- 테스트시에 MockMultipartFile이 Put에서는 입력이 되지 않았지만,
- 커스텀 Request타입을 만들어서 put 헤더에서도 file을 보낼 수 있도록 하였습니다.
**PR에서는 축제부스 도메인에 대한 통합 테스트 로직과 리팩토링 사항이 있습니다. 확인하시고 리뷰해주시면 감사하겠습니다.**
=> [#145] 축제부스 통합 테스트 로직을 작성한다.

src/main/java/com/festival/domain/timetable/controller/TimeTableController.java, src/main/java/com/festival/domain/timetable/repository/impl/TimeTableRepositoryImpl.java, src/main/java/com/festival/domain/timetable/service/TimeTableService.java, src/test/java/com/festival/domain/timetable/controller/TimeTableControllerTest.java, src/test/java/com/festival/domain/timetable/service/TimeTableServiceTest.java
- #153 
- 시간표 도메인의 통합 테스트 로직을 구현하였습니다.
- 시간표 서비스 메소드의 명을 직관적으로 확인할 수 있도록 기존 메소드 명 뒤에 도메인 이름을 추가하였습니다.
- 시간표 목록 메소드에 입력되는 시작시간, 종료시간이 경계값을 가질 경우에는 포함되지 않는 이슈를 확인하였습니다.
- 경계값도 포함되어 조회되도록 조건을 수정하였습니다.
after -> goe (Greater than Or Equal to)
before -> loe (Less than Or Equal to)
**PR에서는 시간표 도메인의 리팩토링 사항, 통합 테스트 로직이 적용되었습니다. 확인하시고, 머지해주시면 감사하겠습니다.**
=> [#153] 시간표 도메인에 대한 통합 테스트 로직을 구현한다.

src/main/java/com/festival/common/util/ValidationUtils.java, src/main/java/com/festival/domain/bambooforest/dto/BamBooForestRes.java, src/main/java/com/festival/domain/guide/controller/GuideController.java, src/main/java/com/festival/domain/guide/dto/GuideReq.java, src/main/java/com/festival/domain/guide/dto/GuideRes.java, src/main/java/com/festival/domain/guide/model/GuideType.java, src/main/java/com/festival/domain/guide/service/GuideService.java, src/test/java/com/festival/domain/guide/controller/GuideControllerTest.java, src/test/java/com/festival/domain/guide/service/GuideServiceTest.java
- #164 
- 안내사항 상태값 중 QNA 상태를 제거했습니다.
- 안내사항의 권한 체크 로직에서 MANAGER를 제외한 ADMIN의 권한만 허용되도록 리팩토링 했습니다.
- 안내사항 도메인에서 이미지는 필수사항이 아니므로 이미지 검증 어노테이션을 제거하였습니다.
=> [#164] 안내사항 도메인의 로직 개선 사항을 적용한다.

src/main/java/com/festival/common/scheduler/SchedulerRunner.java, src/main/java/com/festival/domain/booth/controller/BoothController.java, src/main/java/com/festival/domain/booth/model/Booth.java, src/main/java/com/festival/domain/booth/service/BoothService.java, src/main/java/com/festival/domain/guide/controller/GuideController.java, src/main/java/com/festival/domain/program/controller/ProgramController.java, src/main/java/com/festival/domain/program/model/Program.java, src/main/java/com/festival/domain/program/service/ProgramService.java
- #176 
- 안내사항 도메인에만 적용되던 조회수 증감 로직을 다른 도메인에도 적용시켰습니다.
- 클라이언트의 ip를 받아와서 그값을 redis에 저장하여 게시물 별 조회수 중복을 확인하도록 로직을 구성하였습니다.
- **Domain이름_Id_게시물Number** 형식
=> [#176] 도메인별 조회수 증감 로직을 리팩토링한다.

src/main/java/com/festival/common/util/ValidationUtils.java, src/main/java/com/festival/domain/bambooforest/controller/BambooForestController.java, src/main/java/com/festival/domain/booth/controller/BoothController.java, src/main/java/com/festival/domain/guide/controller/GuideController.java, src/main/java/com/festival/domain/program/controller/ProgramController.java, src/main/java/com/festival/domain/timetable/controller/TimeTableController.java
- #180 
- 커스텀 검증 클래스에서 각 예외 사항 발생시에 커스텀 exception을 throw하고 있는데, 해당 메소드가 실행되는 컨트롤러 계층에서도 exception을 던지고 있었습니다.
- 커스텀 exception이 터진다면 trycatch문이 아닌이상 해당 throw를 잡을 수 없기 때문에 불필요하다 생각하여
- 컨트롤러계층에서 throw 로직을 제거하였습니다.
- 커스텀 검증 클래스에서 private 메소드들을 하단으로 옮기고 public 메소드가 상단에 표시되도록 수정하였습니다.
**PR을 확인하시고, 고쳐야할 점이 있다면 말씀해 주시면 감사하겠습니다.**
=> [#180] 컨트롤러계층에서 throw문 제거

src/main/java/com/festival/domain/booth/controller/BoothController.java, src/main/java/com/festival/domain/booth/controller/dto/BoothRes.java, src/main/java/com/festival/domain/booth/controller/dto/BoothSearchRes.java, src/main/java/com/festival/domain/booth/repository/BoothRepositoryCustom.java, src/main/java/com/festival/domain/booth/repository/impl/BoothRepositoryImpl.java, src/main/java/com/festival/domain/booth/service/BoothService.java, src/main/java/com/festival/domain/guide/dto/GuideRes.java, src/main/java/com/festival/domain/program/controller/ProgramController.java, src/main/java/com/festival/domain/program/dto/ProgramRes.java, src/main/java/com/festival/domain/program/dto/ProgramSearchRes.java, src/main/java/com/festival/domain/program/repository/ProgramRepositoryCustom.java, src/main/java/com/festival/domain/program/repository/impl/ProgramRepositoryCustomImpl.java, src/main/java/com/festival/domain/program/service/ProgramService.java
- #182 
- 축제부스와 프로그램에 대한 검색 기능을 추가하였습니다.
- 현재는 데이터의 양이 많지 않기 때문에 우선은 Like 검색 쿼리로 검색을 하도록 구현하였습니다.
- 이후 데이터양이 많이지게 된다면 리팩토링, 개선할 생각입니다.
=> [#180] 각 도메인에 대한 통합 검색 로직을 추가한다.

build.gradle, src/test/java/com/festival/domain/util/TestRedisConfig.java
- #191 
- 서버에 어플리케이션을 배포하게되면 레디스가 추가된 통합 및 단위 테스트는 레디스를 열결하지 못해 local에서 성공하던 케이스들이 실패하게 됩니다.
- 따라서 테스트 상황시에만 사용할 내장 Redis를 연동하여 어디서든 케이스들이 성공할 수 있도록 의존성을 수정하였습니다.
=> [#191] 상황별 테스트 일괄 통과를 위한 내장 Redis 추가

build.gradle
- #233 
- build시에 생성되는 jar 파일이 0.0.1로 고정되는 문제가 있었습니다.
- yml의 버전과 연동되도록 수정하였습니다.
- 도커파일에서 잘못된 jar 파일 접근을 방지하기 위해
- plain.jar파일의 생성을 false로 수정하였습니다.
=> [#233] 스냅샷 버전 동기화

src/main/java/com/festival/common/security/config/SecurityConfig.java, src/main/java/com/festival/common/security/dto/MemberLoginReq.java, src/main/java/com/festival/domain/booth/controller/BoothController.java, src/main/java/com/festival/domain/member/controller/MemberController.java, src/main/java/com/festival/domain/program/controller/ProgramController.java, src/main/java/com/festival/domain/timetable/controller/TimeTableController.java, src/test/java/com/festival/domain/member/controller/MemberControllerTest.java, src/test/java/com/festival/domain/util/TestRedisConfig.java
- #244 
- Member 통합 테스트 로직을 구현했습니다.
- Member dto에 setter를 추가하였습니다.
- 각 클래스 별 띄어쓰기, 미사용 의존성 제거를 수행했습니다.
=> [#244] Member 도메인 통합 테스트 로직 구현

src/main/java/com/festival/domain/bambooforest/controller/BambooForestController.java, src/main/java/com/festival/domain/bambooforest/repository/impl/BamBooForestRepositoryImpl.java, src/main/java/com/festival/domain/booth/controller/BoothController.java, src/main/java/com/festival/domain/guide/controller/GuideController.java, src/main/java/com/festival/domain/program/controller/ProgramController.java, src/main/java/com/festival/domain/timetable/controller/TimeTableController.java
- #290 
- www-encorded-formData 통신 문제로 모든 POST, PUT요청은 multipart-formData로 대체합니다.
- 추후 이미지를 제외한 데이터에 대해서는 JSON으로 받는게 좋아보입니다.
- 날짜나 타입의 포맷을 알려주기 위해 @ParmeterObject를 사용했습니다.
-> 스웨거에서 파라미터를 받는것으로 인식하기 때문에 description에 설명을 써놔야합니다.
=> [#290] API contentType 통합

src/main/java/com/festival/common/util/ImageUtils.java, src/main/java/com/festival/domain/booth/service/BoothService.java, src/main/java/com/festival/domain/image/service/ImageService.java, src/main/java/com/festival/domain/program/service/ProgramService.java
- #323 
- S3 입출력 로직을 활성화 합니다.
- 기본 이미지 주소가 파일이름으로만 저장되었습니다.
- 주소인만큼 전체 엔드포인트를 포함하여 저장되도록 수정하였습니다.
**imageName -> endpoint/bucketName/folderName/imageName**
=> [#323] S3 입출력 로직 활성화

src/main/java/com/festival/common/exception/ErrorCode.java, src/main/java/com/festival/common/security/JwtAuthenticationFilter.java, src/main/java/com/festival/common/security/JwtTokenProvider.java, src/main/java/com/festival/common/security/dto/JwtTokenRes.java
- #325 
- jwt 인증에 대한 예외처리 로직을 작성했습니다
EMPTY_AUTHORITY("권한 정보가 필요합니다.", HttpStatus.BAD_REQUEST),
INVALID_ACCESS_TOKEN("유효하지 않은 AccessToken입니다.", HttpStatus.BAD_REQUEST),
INVALID_TYPE_ACCESS_TOKEN("AccessToken의 타입은 Bearer입니다.", HttpStatus.BAD_REQUEST),
EXPIRED_PERIOD_ACCESS_TOKEN("기한이 만료된 AccessToken입니다.", HttpStatus.BAD_REQUEST),
- resolveToken보다는 Bearer인지 타입만 검증한 뒤 추출하는 코드이기에 extractBearerToken 으로 변경했습니다.
=> [#325] jwtToken에 대한 예외처리 작성.

src/main/java/com/festival/common/exception/ErrorCode.java, src/main/java/com/festival/common/security/JwtAuthenticationFilter.java, src/main/java/com/festival/common/security/JwtTokenProvider.java, src/main/java/com/festival/common/security/dto/JwtTokenRes.java, src/main/java/com/festival/common/util/JwtTokenUtils.java, src/main/java/com/festival/common/util/SecurityUtils.java, src/main/java/com/festival/domain/member/controller/MemberController.java, src/main/java/com/festival/domain/member/service/MemberService.java
- #331 
- 로그인 시 AccessToken과 RefreshToken을 동시에 발급합니다.
- AccessToken이 만료 됐을 시 토큰 재발급 요청(api/v2/member/rotate)을 통해 AccessToken과 RefreshToken을 재발급 받습니다.
-> 요청 URI는 조금 더 고민해볼 생각입니다.
- 토큰을 생성할 때 List<String> roles를 넘겨서 처리하던 방식에서 Authentication만 넘기고 authorities를 꺼내서 권한 정보를 만드는 방식으로 리팩토링 했습니다.
- 현재 토큰 발급과 재발급 기능만 구현한 상황이며, 다음 작업에서 Redis를 이용해 칩입 탐지 기능을 구현할 예정입니다.
=> [#331] RefreshToken 도입( 발급, 재발급)

src/main/java/com/festival/common/redis/RedisConfig.java, src/main/java/com/festival/common/redis/RedisService.java, src/main/java/com/festival/common/scheduler/SchedulerRunner.java, src/main/java/com/festival/common/security/JwtTokenProvider.java, src/main/java/com/festival/domain/booth/service/BoothService.java, src/main/java/com/festival/domain/guide/service/GuideService.java, src/main/java/com/festival/domain/member/service/MemberService.java, src/main/java/com/festival/domain/program/service/ProgramService.java
- #335 
- isDuplicateAccess메서드의 논리가 반대로 설정돼있어서 수정했습니다.
-> 추가로 중복 체크만 해야 하는 메서드에서 중복설정까지 하고있는 것 같아 역할을 분리했습니다.  
- Redis에 자신의 PK기반으로 RefreshToken을 저장합니다.
-> 침입자가 RefreshToken을 탈취하여 기존의 RefreshToken을 갱신했다면
사용자가 RefreshToken을 이용해 재발급을 시도할 때 침입이 탐지됩니다.
=> [#335] Redis를 이용해 토큰 탈취를 감지

src/main/java/com/festival/common/exception/ErrorCode.java, src/main/java/com/festival/common/redis/EmbeddedRedisConfig.java, src/main/java/com/festival/common/redis/RedisConfig.java, src/main/java/com/festival/common/redis/RedisService.java, src/main/java/com/festival/common/scheduler/SchedulerRunner.java, src/main/java/com/festival/common/security/JwtAuthenticationFilter.java, src/main/java/com/festival/common/security/JwtTokenProvider.java, src/main/java/com/festival/domain/booth/service/BoothService.java, src/main/java/com/festival/domain/guide/service/GuideService.java, src/main/java/com/festival/domain/member/service/MemberService.java, src/main/java/com/festival/domain/program/service/ProgramService.java
- #339 
- refreshToken의 유효성 검증을 작성했습니다.
- 이전 PR 내용 무시하시고 이걸로 이해하시면됩니다.
-> 현재 DB에 있는 토큰과 요청으로 들어오는 토큰이 다르면 토큰 탈취로 간주합니다.
- redis에서 사용자에 대한 key값을 날립니다. -> 로그아웃 처리(다음 이슈에서 처리하겠습니다.)
- 에러 코드를 어떻게 해야 할 지 감이 안와서 일단 SNATCH_TOKEN으로 해두었습니다.
=> [#339]  RefreshToken 검증 및 예외처리

src/main/java/com/festival/common/exception/ErrorCode.java, src/main/java/com/festival/common/redis/EmbeddedRedisConfig.java, src/main/java/com/festival/common/redis/RedisService.java, src/main/java/com/festival/common/scheduler/SchedulerRunner.java, src/main/java/com/festival/common/security/JwtAuthenticationFilter.java, src/main/java/com/festival/common/security/JwtTokenProvider.java, src/main/java/com/festival/domain/member/controller/MemberController.java, src/main/java/com/festival/domain/member/service/MemberService.java
- #341 
- 저장소(Redis)에 PK를 key값으로 RefreshToken이 등록 돼 있으면 로그인한 것으로 간주합니다.
- 이에 따라 유효한 accessToken을 가지고 접근했을 때에도 로그아웃 처리 돼 있다면 만료된 토큰으로 예외 처리합니다.
- 기존의 GlobalExceptionHandler는 컨트롤러 단의 예외를 처리하는 것으로 Filter예외 처리를 따로 작성했습니다.
- 이미 존재하는 아이디에 대한 처리를 하는 메서드명을 수정했습니다. isExistId
=> [#341] 로그아웃 기능 구현 및 필터 예외 처리
